CREATE TABLE actors
(
    id         INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name       VARCHAR(255),                                -- Nombre del actor
    occupation VARCHAR(255),                                -- Ocupación del actor
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- Fecha y hora de creación del actor
);

CREATE INDEX idx_actors_name ON actors (name);

CREATE TYPE emotion_enum AS ENUM ('POSITIVE', 'NEGATIVE', 'NEUTRAL');

CREATE TABLE actor_mentions
(
    id              INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    actor_id        INT REFERENCES actors (id) ON DELETE CASCADE,
    platform_source TEXT         NOT NULL,              -- Dominio
    url_source      TEXT         NOT NULL,              -- URL de la mención
    type            TEXT         NOT NULL,              -- Tipo (Online News, Facebook Public, X, etc...)
    title           TEXT         NOT NULL,              -- Título de la mención
    sentiment       emotion_enum NOT NULL,              -- Sentimiento del actor en la mención (POSITIVE, NEGATIVE, NEUTRAL)
    content         TEXT         NOT NULL,              -- Lo que se menciono por el actor (Snippet)
    topic           VARCHAR(255) NOT NULL,              -- Tema principal de la mención (elección, title o LLM)
    mention_date    TIMESTAMP    NOT NULL,              -- Fecha y hora de la mención
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Fecha y hora de creación de la mención
);

CREATE INDEX idx_mentions_actor_id ON actor_mentions (actor_id);
CREATE INDEX idx_mentions_topic ON actor_mentions (topic);
CREATE INDEX idx_mentions_mention_date ON actor_mentions (mention_date);

CREATE TABLE actor_mention_trends
(
    id            INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    actor_id      INT REFERENCES actors (id) ON DELETE CASCADE,
    topic         VARCHAR(255) NOT NULL, -- El tema que se repite (ej. Reforma educativa)
    frequency     INT          NOT NULL, -- Número de veces que se mencionó el tema
    first_mention TIMESTAMP    NOT NULL, -- Primera vez que se mencionó el tema
    last_mention  TIMESTAMP    NOT NULL, -- Última vez que se mencionó el tema
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_mention_trends_actor_id ON actor_mention_trends (actor_id);
CREATE INDEX idx_mention_trends_topic ON actor_mention_trends (topic);

CREATE TABLE mentions -- Guardar menciones no relevantes pero que Brandwatch provee
(
    id              INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    platform_source TEXT      NOT NULL,                 -- Dominio
    url_source      TEXT      NOT NULL,                 -- URL de la mención
    type            TEXT      NOT NULL,                 -- Tipo (Online News, Facebook Public, X, etc...)
    title           TEXT      NOT NULL,                 -- Título de la mención
    content         TEXT      NOT NULL,                 -- Lo que se menciono
    mention_date    TIMESTAMP NOT NULL,                 -- Fecha y hora de la mención
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP -- Fecha y hora de creación de la mención
);

CREATE TYPE importance_level_enum AS ENUM ('HIGH', 'MEDIUM', 'LOW', 'NONE');

CREATE TABLE alerts
(
    id                INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    actor_mention_id  INT REFERENCES actor_mentions (id) ON DELETE CASCADE,
    actor_importance  importance_level_enum NOT NULL,               -- Nivel de importancia del actor (HIGH, MEDIUM, LOW, NONE)
    topic_importance  importance_level_enum NOT NULL,               -- Nivel de importancia del tema (HIGH, MEDIUM, LOW, NONE)
    source_importance FLOAT                 NOT NULL,               -- Nivel de importancia de la fuente (1.0, 0.75, 0)
    weighing          int                   NOT NULL,               -- Nivel final de importancia de la mención (0-100)
    active            BOOLEAN               NOT NULL DEFAULT FALSE, -- Indica si la alerta está activa o no
    trigger_date      TIMESTAMP             NULL,                   -- Fecha y hora en que se disparó la alerta
    deactivated_at    TIMESTAMP                                     -- Fecha y hora en que se desactivó la alerta
);

CREATE INDEX idx_alerts_actor_mention_id ON alerts (actor_mention_id);

CREATE TABLE queries
(
    id                INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    query_id          VARCHAR(255) NOT NULL,
    last_mention_date TIMESTAMP    NOT NULL
);

CREATE INDEX idx_query_query_id ON queries (query_id);

CREATE TABLE media_ranking
(
    id          INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    Media       TEXT  NOT NULL,
    Domain      TEXT  NOT NULL,
    Country     TEXT  NOT NULL,
    Region      TEXT  NOT NULL,
    Language    TEXT  NOT NULL,
    Typology    TEXT  NOT NULL,
    Global_rank INT   NOT NULL,
    Overall     FLOAT NOT NULL,
    Score       FLOAT NOT NUll
);

CREATE INDEX idx_media_ranking_domain ON media_ranking (Domain);


-- Primer insert de ranking de medios
INSERT INTO "media_ranking" (Media, Domain, Country, Region, Language, Typology, Global_rank, Overall, Score)
VALUES ('El Financiero', 'elfinanciero.com.mx', 'Mexico', 'Latin America', 'Spanish', 'Finance', '107', '66.75', '1'),
       ('La Jornada', 'jornada.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '338', '59.5', '1'),
       ('Excélsior', 'excelsior.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '351', '59.25', '1'),
       ('EL UNIVERSAL', 'eluniversal.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '425', '57.75',
        '1'),
       ('EL HERALDO DE MÉXICO', 'heraldodemexico.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '489',
        '56.75', '1'),
       ('El Economista', 'eleconomista.com.mx', 'Mexico', 'Latin America', 'Spanish', 'Finance', '547', '55.75', '1'),
       ('EL SOL DE MÉXICO', 'elsoldemexico.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '567', '55.5',
        '1'),
       ('PROCESO', 'proceso.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '599', '55', '1'),
       ('MILENIO', 'milenio.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '729', '53.25', '1'),
       ('SDP NOTICIAS', 'sdpnoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1031', '50', '1'),
       ('El Informador', 'informador.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1171', '48.75', '1'),
       ('Expansión', 'expansion.mx', 'Mexico', 'Latin America', 'Spanish', 'Finance', '1171', '48.75', '1'),
       ('Animal Político', 'animalpolitico.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1171', '48.75',
        '1'),
       ('Récord', 'record.com.mx', 'Mexico', 'Latin America', 'Spanish', 'Sports', '1246', '48.25', '1'),
       ('PULSO', 'pulsoslp.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1246', '48.25', '1'),
       ('EL DEBATE', 'debate.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1276', '48', '1'),
       ('ARISTEGUI NOTICIAS', 'aristeguinoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1276',
        '48', '1'),
       ('REFORMA', 'reforma.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1362', '47.25', '1'),
       ('LA CRÓNICA DE HOY', 'cronica.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1362', '47.25',
        '1'),
       ('Forbes México', 'forbes.com.mx', 'Mexico', 'Latin America', 'Spanish', 'Finance', '1423', '46.75', '1'),
       ('SIN EMBARGO', 'sinembargo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1517', '46', '1'),
       ('LA RAZÓN', 'razon.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1517', '46', '1'),
       ('Business Insider Mexico', 'businessinsider.mx', 'Mexico', 'Latin America', 'Spanish', 'Finance', '1517', '46',
        '1'),
       ('LA SILLA ROTA', 'lasillarota.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1590', '45.5', '1'),
       ('PUBLIMETRO', 'publimetro.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1748', '44.5',
        '0.75'),
       ('Esto', 'esto.com.mx', 'Mexico', 'Latin America', 'Spanish', 'Sports', '1748', '44.5', '0.75'),
       ('EL SIGLO', 'elsiglodetorreon.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1748', '44.5',
        '0.75'),
       ('QUADRATÍN', 'quadratin.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1790', '44.25', '1'),
       ('EL IMPARCIAL', 'elimparcial.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1850', '43.75', '1'),
       ('ZETA', 'zetatijuana.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1890', '43.5', '0.75'),
       ('DIARIO DE YUCATÁN', 'yucatan.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1927', '43.25',
        '0.75'),
       ('CAMBIO DE MICHOACÁN', 'cambiodemichoacan.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1927',
        '43.25', '0.75'),
       ('NOROESTE', 'noroeste.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '1963', '43', '1'),
       ('EL NORTE', 'elnorte.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '1963', '43', '1'),
       ('UNO MÁS UNO', 'unomasuno.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2023', '42.5', '1'),
       ('BASTA!', 'diariobasta.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2023', '42.5', '0.75'),
       ('LA PRENSA', 'la-prensa.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2056', '42.25', '0.75'),
       ('EL SOL DE TOLUCA', 'elsoldetoluca.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2056',
        '42.25', '1'),
       ('DIARIO DE QUERÉTARO', 'diariodequeretaro.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2056',
        '42.25', '1'),
       ('IMAGEN', 'imagenzac.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2095', '42', '1'),
       ('EL PORVENIR', 'elporvenir.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2095', '42', '1'),
       ('DIARIO DE MORELOS', 'diariodemorelos.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2132',
        '41.75', '1'),
       ('EL SOL DE HIDALGO', 'elsoldehidalgo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2179',
        '41.5', '1'),
       ('ABC DE MONTERREY', 'abcnoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2179', '41.5',
        '1'),
       ('EL IMPARCIAL', 'imparcialoaxaca.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2212', '41.25',
        '1'),
       ('EL SUR', 'suracapulco.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2255', '41', '1'),
       ('EL SOL DE SINALOA', 'elsoldesinaloa.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2255',
        '41', '1'),
       ('EL DIARIO DE JUÁREZ', 'diario.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2255', '41', '1'),
       ('DIARIO DE COLIMA', 'diariodecolima.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2297', '40.75',
        '0.75'),
       ('EL HERALDO DE SALTILLO', 'elheraldodesaltillo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2395', '40.25', '1'),
       ('LA JORNADA DE ORIENTE', 'lajornadadeoriente.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2443', '40', '1'),
       ('EL SOL DE TAMPICO', 'elsoldetampico.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2443',
        '40', '1'),
       ('EL SOL DE PUEBLA', 'elsoldepuebla.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2443', '40',
        '1'),
       ('EL HERALDO DE CHIHUAHUA', 'elheraldodechihuahua.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2443', '40', '1'),
       ('NORTE', 'nortedigital.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2515', '39.5', '1'),
       ('NORESTE', 'noreste.net', 'Mexico', 'Latin America', 'Spanish', 'General News', '2515', '39.5', '1'),
       ('LA VERDAD YUCATÁN', 'laverdadnoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2515',
        '39.5', '1'),
       ('EL SOL DE ZACATECAS', 'elsoldezacatecas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2560',
        '39.25', '1'),
       ('EL SOL DE IRAPUATO', 'elsoldeirapuato.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2560',
        '39.25', '1'),
       ('EL HERALDO', 'elheraldoslp.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2560', '39.25',
        '1'),
       ('Reporte índigo', 'reporteindigo.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2588', '39', '1'),
       ('EL SOL DE SAN LUIS', 'elsoldesanluis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2588',
        '39', '1'),
       ('CORREO', 'periodicocorreo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2631', '38.75', '1'),
       ('MÁS NOTICIAS', 'masnoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2631', '38.75', '1'),
       ('LA VOZ DE MICHOACÁN', 'lavozdemichoacan.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2707',
        '38.25', '1'),
       ('DIARIO XALAPA', 'diariodexalapa.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2707', '38.25',
        '1'),
       ('CUARTO PODER', 'cuartopoder.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2707', '38.25',
        '0.75'),
       ('24 HORAS', '24-horas.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2707', '38.25', '1'),
       ('ROTATIVO', 'rotativo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2751', '38', '0.75'),
       ('NOVEDADES DE TABASCO', 'novedadesdetabasco.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2751', '38', '0.75'),
       ('INFO7', 'info7.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2751', '38', '0.75'),
       ('EL SOL DE HERMOSILLO', 'elsoldehermosillo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2751', '38', '1'),
       ('LA JORNADA VERACRUZ', 'jornadaveracruz.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2795',
        '37.75', '1'),
       ('EL SOL DE MORELIA', 'elsoldemorelia.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2795',
        '37.75', '1'),
       ('EL SOL DE CUERNAVACA', 'elsoldecuernavaca.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '2795', '37.75', '1'),
       ('EL SIGLO', 'elsiglodedurango.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2795', '37.75',
        '1'),
       ('LA UNIÓN DE MORELOS', 'launion.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2832', '37.5',
        '1'),
       ('LA JORNADA MAYA', 'lajornadamaya.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2832', '37.5',
        '1'),
       ('LA JORNADA HIDALGO', 'lajornadahidalgo.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2870',
        '37.25', '1'),
       ('EL SOL DE TLAXCALA', 'elsoldetlaxcala.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2870',
        '37.25', '1'),
       ('EL SOL DE LEÓN', 'elsoldeleon.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2870', '37.25',
        '1'),
       ('EL SUDCALIFORNIANO', 'elsudcaliforniano.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2909',
        '37', '0.75'),
       ('EL HORIZONTE', 'elhorizonte.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2909', '37', '0.75'),
       ('QUINTA FUERZA', 'quintafuerza.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2949', '36.75',
        '0.75'),
       ('EL TIEMPO', 'eltiempomonclova.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2949', '36.75',
        '0.75'),
       ('EL DIARIO NTR', 'ntrguadalajara.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '2982', '36.5',
        '1'),
       ('ENTRE LÍNEAS', 'entrelineas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2982', '36.5',
        '0.75'),
       ('EL GRÁFICO', 'elgrafico.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '2982', '36.5', '0'),
       ('EL OCCIDENTAL', 'eloccidental.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3021', '36.25',
        '0.75'),
       ('EL HERALDO DE CHIAPAS', 'elheraldodechiapas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3075', '36', '1'),
       ('EL SUR', 'diariodelsur.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3075', '36', '0.75'),
       ('CENTRAL', 'periodicocentral.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105', '35.75',
        '0.75'),
       ('EXPRESO', 'expreso.press', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105', '35.75', '0.75'),
       ('EL MEXICANO', 'el-mexicano.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105', '35.75',
        '0.75'),
       ('EL MAÑANA', 'elmanana.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105', '35.75', '0.75'),
       ('EL DIARIO DE CIUDAD VICTORIA', 'eldiariomx.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105',
        '35.75', '1'),
       ('24 HORAS PUEBLA', '24horaspuebla.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3105', '35.75',
        '1'),
       ('LA JORNADA SAN LUIS', 'lajornadasanluis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3149',
        '35.5', '1'),
       ('INTOLERANCIA', 'intoleranciadiario.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3149', '35.5',
        '0.75'),
       ('EXPRESO', 'expreso.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3149', '35.5', '0.75'),
       ('EL SOL DEL TIJUANA', 'elsoldetijuana.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3149',
        '35.5', '1'),
       ('CONTEXTO', 'contextodedurango.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3149', '35.5',
        '0.75'),
       ('IMAGEN', 'imagendeveracruz.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3194', '35.25', '1'),
       ('AFN', 'afntijuana.info', 'Mexico', 'Latin America', 'Spanish', 'General News', '3194', '35.25', '1'),
       ('EL SOL DE CÓRDOBA', 'elsoldecordoba.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3231',
        '35', '1'),
       ('EL SOL DE ACAPULCO', 'elsoldeacapulco.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3231',
        '35', '1'),
       ('EL DIARIO DE CHIHUAHUA', 'eldiariodechihuahua.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3231', '35', '1'),
       ('EL DICTAMEN', 'eldictamen.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3280', '34.75', '1'),
       ('Distintas Latitudes', 'distintaslatitudes.net', 'Mexico', 'Latin America', 'Spanish', 'General News', '3280',
        '34.75', '0.75'),
       ('AMANECER', 'diarioamanecer.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3280', '34.75',
        '0.75'),
       ('RÍO DOCE', 'riodoce.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3312', '34.5', '0.75'),
       ('NOTICIAS', 'nvinoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3312', '34.5', '0.75'),
       ('EL SOL DEL CENTRO', 'elsoldelcentro.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3312',
        '34.5', '1'),
       ('24 HORAS QUINTANA ROO', '24horasqroo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3312', '34.5',
        '1'),
       ('NOTICIAS VERPERTINAS', 'noticiasvespertinas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3364', '34.25', '0.75'),
       ('EL SOL DE MAZATLÁN', 'elsoldemazatlan.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3364',
        '34.25', '1'),
       ('EJE CENTRAL', 'ejecentral.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3364', '34.25',
        '0.75'),
       ('DIARIO DE MÉXICO', 'diariodemexico.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3364', '34.25',
        '1'),
       ('LA VOZ', 'periodicolavoz.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3405', '34', '1'),
       ('LA JORNADA DE BAJA CALIFORNIA', 'jornadabc.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3405', '34', '1'),
       ('EL MERCURIO DE TAMAULIPAS', 'elmercurio.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3405',
        '34', '0.75'),
       ('EL HERALDO DE TABASCO', 'elheraldodetabasco.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3405', '34', '1'),
       ('CONTRA RÉPLICA', 'contrareplica.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3405', '34',
        '0.75'),
       ('CONTACTO HOY', 'contactohoy.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3405', '34',
        '0.75'),
       ('TRIBUNA', 'tribunacampeche.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3444', '33.75',
        '0.75'),
       ('MTP NOTICIAS', 'mtpnoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3444', '33.75',
        '0.75'),
       ('EL HERALDO DE JUAREZ', 'elheraldodejuarez.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '3444', '33.75', '1'),
       ('CAMBIO', 'diariocambio.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3484', '33.5', '0.75'),
       ('HIDROCÁLIDO', 'hidrocalidodigital.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3528', '33.25',
        '0.75'),
       ('XEU', 'xeu.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3563', '33', '0.75'),
       ('LUCES DEL SIGLO', 'lucesdelsiglo.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3563', '33',
        '0.75'),
       ('EL SOL DE DURANGO', 'elsoldedurango.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3563',
        '33', '1'),
       ('TRIBUNA NOTICIAS', 'tribunanoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3610', '32.75',
        '0.75'),
       ('TRÁFICO ZMG', 'traficozmg.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3610', '32.75', '0.75'),
       ('PSN EN LÍNEA', 'psn.si', 'Mexico', 'Latin America', 'Spanish', 'General News', '3610', '32.75', '0.75'),
       ('MURAL', 'mural.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3610', '32.75', '0.75'),
       ('EL POPULAR', 'elpopular.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3610', '32.75', '0.75'),
       ('MILED MÉXICO', 'miled.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3654', '32.5', '0.75'),
       ('TABASCO HOY', 'tabascohoy.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3722', '32', '1'),
       ('LA PRENSA', 'laprensa.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3722', '32', '1'),
       ('EL SOL DE NAYARIT', 'elsoldenayarit.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3722', '32',
        '1'),
       ('EL QUINTANA ROO', 'elquintanaroo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3722', '32',
        '0.75'),
       ('TRIBUNA DE SAN LUIS', 'tribunadesanluis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3761',
        '31.75', '0.75'),
       ('CAMPECHE HOY', 'campechehoy.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3761', '31.75',
        '0.75'),
       ('HERALDO DE AGUASCALIENTES', 'heraldo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3792', '31.5',
        '1'),
       ('NEWS REPORT MX', 'newsreportmx.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3828', '31.25',
        '0.75'),
       ('EL PUNTERO', 'elpuntero.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3828', '31.25',
        '0.75'),
       ('PORTAL', 'diarioportal.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3828', '31.25', '0.75'),
       ('CAPITAL DE MÉXICO', 'capitalmexico.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3828',
        '31.25', '0.75'),
       ('THE NEWS', 'thenews.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3863', '31', '0.75'),
       ('LA VERDAD DE TAMAULIPAS', 'laverdad.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3863',
        '31', '0.75'),
       ('A.M. DE QUERÉTARO', 'amqueretaro.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3863', '31',
        '0.75'),
       ('MÁS POR MÁS', 'maspormas.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3891', '30.75', '0.75'),
       ('IMPACTO', 'impacto.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3891', '30.75', '0.75'),
       ('PRESENTE', 'diariopresente.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3891', '30.75', '0.75'),
       ('CAFÉ NEGRO', 'cafenegroportal.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3954', '30.25',
        '0.75'),
       ('VANGUARDIA', 'vanguardiaveracruz.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3988', '30',
        '0.75'),
       ('SÍNTESIS', 'sintesis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '3988', '30', '0.75'),
       ('MEGALÓPOLIS', 'megalopolismx.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3988', '30', '0.75'),
       ('COLIMA NOTICIAS', 'colimanoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '3988', '30',
        '0.75'),
       ('NSS OAXACA', 'nssoaxaca.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4028', '29.75', '0.75'),
       ('NOTICIAS', 'noticiasdequeretaro.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4028', '29.75',
        '0.75'),
       ('EL PUNTO CRÍTICO', 'elpuntocritico.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4028', '29.75',
        '0.75'),
       ('PÁGINA 24', 'pagina24.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4054', '29.5', '0.75'),
       ('NOTIMUNDO', 'notimundo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4054', '29.5', '0.75'),
       ('NNC', 'nnc.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4054', '29.5', '0.75'),
       ('BCS NOTICIAS', 'bcsnoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4054', '29.5', '0.75'),
       ('NOVENTA GRADOS', 'noventagrados.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4104', '29.25',
        '0.75'),
       ('LA TARDE', 'latarde.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4104', '29.25', '0.75'),
       ('EXPRÉS', 'elexpres.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4104', '29.25', '0.75'),
       ('DIARIO IMAGEN', 'diarioimagenqroo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4104', '29.25',
        '1'),
       ('PUNTUAL', 'diariopuntual.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4139', '29', '0.75'),
       ('CRONISTA', 'cronista.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4139', '29', '1'),
       ('ALERTA CHIAPAS', 'alertachiapas.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4139', '29',
        '0.75'),
       ('PUNTO MEDIO', 'puntomedio.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4171', '28.75', '0.75'),
       ('MERIDIANO', 'meridiano.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4196', '28.5', '0.75'),
       ('EL LIBERAL DEL SUR', 'liberal.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4196', '28.5',
        '0.75'),
       ('EL HERALDO DE PUEBLA', 'heraldodepuebla.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4196',
        '28.5', '1'),
       ('EL INDEPENDIENTE', 'diarioelindependiente.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4196',
        '28.5', '0.75'),
       ('EL ARSENAL', 'elarsenal.net', 'Mexico', 'Latin America', 'Spanish', 'General News', '4222', '28.25', '0.75'),
       ('8 COLUMNAS', '8columnas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4222', '28.25',
        '0.75'),
       ('YUCATÁN A LA MANO', 'yucatanalamano.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4298', '27.5',
        '0.75'),
       ('Cancha', 'cancha.com', 'Mexico', 'Latin America', 'Spanish', 'Sports', '4298', '27.5', '0.75'),
       ('EL INFORMANTE', 'elinformante.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4326', '27.25',
        '0.75'),
       ('CRÓNICA DE XALAPA', 'cronicadexalapa.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4326',
        '27.25', '1'),
       ('LA RED NOTICIAS', 'larednoticias.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4348', '27',
        '0.75'),
       ('METRÓPOLI', 'grupometropoli.net', 'Mexico', 'Latin America', 'Spanish', 'General News', '4348', '27', '0.75'),
       ('ECOS DE LA COSTA', 'ecosdelacosta.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4348', '27',
        '0.75'),
       ('A TIEMPO', 'atiempo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4364', '26.75', '0.75'),
       ('VALLARTA TODAY', 'vallartatoday.com', 'Mexico', 'Latin America', 'English', 'General News', '4386', '26.5',
        '0.75'),
       ('AL CHILE!', 'alchile.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4418', '26.25', '0.75'),
       ('PUEBLA NOTICIAS', 'pueblanoticias.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4441', '26',
        '0.75'),
       ('NOTIVER', 'notiver.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4441', '26', '0.75'),
       ('EL HERALDO DE VERACRUZ', 'elheraldodeveracruz.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '4441', '26', '1'),
       ('EL GRÁFICO', 'elgraficotam.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4441', '26', '0'),
       ('EDOMEX AL DÍA', 'edomexaldia.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4441', '26', '0.75'),
       ('CONTRAPARTE', 'contraparte.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4441', '26', '0.75'),
       ('CAPITAL ESTADO DE MÉXICO', 'capitaledomex.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '4441', '26', '0.75'),
       ('TIEMPO', 'tiempodigital.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4482', '25.75', '0.75'),
       ('DIGITAL MEX', 'digitalmex.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4482', '25.75', '0.75'),
       ('EXPRESO', 'expresochiapas.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4516', '25.5', '0.75'),
       ('PUNTUAL', 'diario-puntual.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4516', '25.5',
        '0.75'),
       ('ENFOQUE', 'periodicoenfoque.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4548', '25.25',
        '0.75'),
       ('CRÓNICA DE HOY HIDALGO', 'cronicahidalgo.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4548',
        '25.25', '1'),
       ('OPINIÓN SONORA', 'opinionsonora.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4578', '25',
        '0.75'),
       ('EL NOTICIERO', 'elnoticieroenlinea.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4578', '25',
        '0.75'),
       ('EL MUNDO', 'diarioelmundo.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4578', '25', '0.75'),
       ('DIARIO DE TABASCO', 'diariodetabasco.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4578', '25',
        '1'),
       ('24 MORELOS', '24morelos.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4578', '25', '0.75'),
       ('HERALDO ESTADO DE MÉXICO', 'hgrupoeditorial.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4600',
        '24.75', '1'),
       ('TRES PM', 'trespm.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4616', '24.5', '0.75'),
       ('Código Magenta', 'codigomagenta.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4616', '24.5',
        '0.75'),
       ('SINALOA EN LÍNEA', 'sinaloaenlinea.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25',
        '0.75'),
       ('RI OAXACA', 'rioaxaca.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25', '0.75'),
       ('NOTICIAS EN LA MIRA', 'noticiasenlamira.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648',
        '24.25', '0.75'),
       ('MURAL CHIAPAS', 'muralchiapas.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25',
        '0.75'),
       ('EL HERALDO', 'heraldoleon.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25', '1'),
       ('CÓDIGO QRO', 'codigoqro.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25', '0.75'),
       ('AFMEDIOS', 'afmedios.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4648', '24.25', '0.75'),
       ('20 MINUTOS mx', '20minutos.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4699', '23.75',
        '1'),
       ('PRESS LIBRE', 'presslibre.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4722', '23.5', '0.75'),
       ('IMPULSO', 'impulsoedomex.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4722', '23.5',
        '0.75'),
       ('CENTRAL DE NOTICIAS', 'centraldenoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4722',
        '23.5', '0.75'),
       ('EXCLUSIVAS PUEBLA', 'exclusivaspuebla.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4738',
        '23.25', '0.75'),
       ('SN DIGITAL', 'sndigital.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4759', '23', '0.75'),
       ('PÁSALA', 'pasala.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4759', '23', '0.75'),
       ('LA ROJA', 'laroja.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4759', '23', '0.75'),
       ('PAUSA', 'pausa.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4786', '22.75', '0.75'),
       ('EL REGIONAL DEL SUR', 'elregional.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4786',
        '22.75', '0.75'),
       ('ABC DE MICHOACÁN', 'diarioabcdemichoacan.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4786',
        '22.75', '1'),
       ('ABC', 'abctlax.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4786', '22.75', '1'),
       ('PALCO NOTICIAS', 'palcoquintanarroense.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4806',
        '22.5', '0.75'),
       ('EXTRAOFICIAL', 'extraoficial.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4822', '22.25',
        '0.75'),
       ('ENFOQUE INFORMATIVO', 'enfoquenayarit.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4822',
        '22.25', '0.75'),
       ('ULTRANOTICIAS', 'ultranoticias.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4845', '22',
        '0.75'),
       ('EL HERALDO DE COATZACOALCOS', 'heraldodecoatzacoalcos.com.mx', 'Mexico', 'Latin America', 'Spanish',
        'General News', '4864', '21.75', '1'),
       ('EL BRAVO', 'elbravo.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4864', '21.75', '0.75'),
       ('AGENCIA DE NOTICIAS SLP', 'agenciadenoticiasslp.com', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '4864', '21.75', '0.75'),
       ('MOMENTO', 'periodicoelmomento.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4903', '21.25',
        '0.75'),
       ('DIARIO DE POZA RICA', 'elheraldodepozarica.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '4903', '21.25', '1'),
       ('CRÍTICA DN', 'criticadn.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4913', '21', '0.75'),
       ('NOTICIAS GDL', 'noticiasgdl.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4928', '20.75',
        '0.75'),
       ('EL PERIÓDICO DE TLAXCALA', 'elperiodicodetlaxcala.com', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '4928', '20.75', '0.75'),
       ('EL DÍA', 'periodicoeldia.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4945', '20.5', '0.75'),
       ('MOMENTO', 'diariomomento.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4945', '20.5', '0.75'),
       ('EL HERALDO DE XALAPA', 'heraldodexalapa.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4968',
        '20.25', '1'),
       ('GM NOTICIAS', 'gmnoticias.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '4968', '20.25', '0.75'),
       ('DURANGO PRESS', 'durangopress.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4968', '20.25',
        '0.75'),
       ('QUERÉTARO 24 7', 'queretaro24-7.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4983', '20',
        '0.75'),
       ('OAXACA HOY', 'oaxacahoy.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4983', '20', '0.75'),
       ('AGENDA TLAXCALA', 'agendatlaxcala.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4983', '20',
        '0.75'),
       ('EXPRESO QUERÉTARO', 'expresoqueretaro.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '4996',
        '19.75', '0.75'),
       ('LA OPINIÓN', 'laopinionpuebla.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5025', '19.25',
        '0.75'),
       ('DIARIO DE PUEBLA', 'diariodepuebla.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5042', '19',
        '1'),
       ('REALIDADES', 'realidadessperiodico.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5063', '18.75',
        '0.75'),
       ('CENTURIA', 'centuria.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5063', '18.75', '0.75'),
       ('NOTICIAS NUEVO LEÓN', 'noticiasnuevoleon.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5089',
        '18.5', '0.75'),
       ('EL DECIDOR', 'eldecidor.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5089', '18.5', '0.75'),
       ('LA JORNADA MORELOS', 'lajornadamorelos.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5118',
        '18', '1'),
       ('YUCATÁN AL MOMENTO', 'yucatanalmomento.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5131',
        '17.75', '0.75'),
       ('NOTICIAS NPI', 'noticiasnpi.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5144', '17.5',
        '0.75'),
       ('LA VOZ DE TABASCO', 'lavozdetabasco.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5144',
        '17.5', '0.75'),
       ('SINALOA HOY', 'sinaloahoy.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5156', '17.25',
        '0.75'),
       ('EN CONTACTO', 'encontacto.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5156', '17.25',
        '0.75'),
       ('LA VOZ DE SAN LUIS', 'lavozdesanluis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5167',
        '17', '0.75'),
       ('TERMÁPOLIS', 'termapolis.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5181', '16.75',
        '0.75'),
       ('AHORA NOTICIAS', 'ahoranoticias.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5181', '16.75',
        '0.75'),
       ('ENFOQUE', 'enfoquemonterrey.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5204', '16.25',
        '0.75'),
       ('LA CALLE', 'lacallelibre.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5216', '16', '0.75'),
       ('AL CONTACTO', 'alcontacto.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5216', '16', '0.75'),
       ('TRIBUNA DE LA PAZ', 'tribunadelapaz.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5236',
        '15.75', '0.75'),
       ('PORTAVOZ', 'portavozchiapas.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5251', '15.5',
        '0.75'),
       ('LA TRIBUNA', 'latribuna.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5251', '15.5', '0.75'),
       ('CURSOR EN LA NOTICIA', 'cursorenlanoticia.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News',
        '5277', '15', '0.75'),
       ('PUEBLA AHORA', 'pueblaahora.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5291', '14.75',
        '0.75'),
       ('JUÁREZ A DIARIO', 'juarezadiario.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5291', '14.75',
        '0.75'),
       ('NOTICIAS SAN LUIS', 'noticias-sanluis.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5304',
        '14.5', '0.75'),
       ('CRÓNICA DE CAMPECHE', 'cronicacampeche.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5304',
        '14.5', '1'),
       ('REPORTE 18', 'reporte18.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5314', '14.25', '0.75'),
       ('DEBATE', 'diariodebate.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5314', '14.25', '0.75'),
       ('EL VESPERTINO', 'periodicoelvespertino.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5326',
        '14', '0.75'),
       ('CAMBIO 21', 'cambio21.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5338', '13.75', '0.75'),
       ('EL IMPARCIAL', 'elimparcialdenayarit.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5347',
        '13.5', '1'),
       ('ZACATECAS AL MINUTO', 'zacatecasalminuto.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5360',
        '13', '0.75'),
       ('RC NOTICIAS', 'rcnoticias.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5373', '12.5',
        '0.75'),
       ('SAN LUIS INFORMA', 'sanluisinforma.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5380', '12.25',
        '0.75'),
       ('LA PRENSA SONORA', 'laprensasonora.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5395', '11.75',
        '0.75'),
       ('EL EDÉN MX', 'eledenmx.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5405', '11.5', '0.75'),
       ('EL PLANETA', 'elplaneta.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5412', '11.25', '0.75'),
       ('EL DIARIO DE MATAMOROS', 'diariodematamoros.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5412',
        '11.25', '1'),
       ('CENSURA', 'diariocensura.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5419', '11', '0.75'),
       ('HOY NOVEDADES', 'elnovedades.com.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5424', '10.75',
        '0.75'),
       ('EL DIARIO DE TLAXCALA', 'eldiariodetlaxcala.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5424',
        '10.75', '1'),
       ('LA OPINIÓN', 'laopiniondetamaulipas.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5442', '10',
        '0.75'),
       ('ADN INFORMA', 'adninforma.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5442', '10', '0.75'),
       ('EL NORTEÑO', 'periodicoelnorteno.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5452', '8.75',
        '0.75'),
       ('NUEVO DIARIO TABASCO', 'nuevodiariotabasco.com', 'Mexico', 'Latin America', 'Spanish', 'General News', '5452',
        '8.75', '0.75'),
       ('MERIDIANO DE HOY', 'meridianodehoy.mx', 'Mexico', 'Latin America', 'Spanish', 'General News', '5455', '8.5',
        '0.75');
